### PR TITLE
Adding home page for Yiqin

### PR DESCRIPTION
**Pull request by YiqinZhao**

### CODE REVIEW

**Comment by KimYangOfCat** [comment]
I don't understand what anything needed me to review is?

**Review by KimYangOfCat — COMMENTED** [review]
OK, I have reviewed the changes. No problem, I think~

**Comment by YiqinZhao** [comment]
@Arabaku Looks good to you? If so, please merge.

**Comment by seiuryuu** [comment]
Thanks, merged!

**Pull request merged**
