### PR TITLE
Assets URL Transfer to Eyire

### PR DESCRIPTION
**Pull request by YiqinZhao**
The original file storage system on DigitalOcean Space S3 compatible service is going to shutdown. All previous assets will be transfer to my new service eyrie.coden.hk. This PR replaced all associated URLs to new address.

### CODE REVIEW

**Review by KimYangOfCat — COMMENTED** [review]
I think no problem!

**Comment by YiqinZhao** [comment]
@Arabaku Looks good to you? If so, please merge.

**Comment by KimYangOfCat** [comment]
@YiqinZhao He's busy at the Japanese exam recently. Didn't you migrate the Server back again? Are you sure this request is unspent?

**Comment by YiqinZhao** [comment]
Yes, I did two migration. And I have checked, this PR runs good on my machine. Can you take a look?

**Comment by seiuryuu** [comment]
Thanks, merged!

**Pull request merged**
